name: Daily Sports Video
on:
  workflow_dispatch:
  schedule:
    - cron: '45 12 * * *' # नेपालको साँझ ६:३० बजे

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip install Pillow==9.5.0 moviepy==1.0.3 requests beautifulsoup4 edge-tts
      - name: Run Sports Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PEXELS_KEY: ${{ secrets.PEXELS_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python sports_video.py
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-sports-video
          path: sports_final.mp4
