name: Daily Tender Bot
on:
  workflow_dispatch: # Aile manual test ko lagi matrai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Python version badhayeko

      - name: Install latest dependencies
        run: |
          pip install --upgrade google-generativeai requests # Upgrade thapeko

      - name: Run tender bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
