name: Generate My Video
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y ffmpeg
    - name: Run video generator
      run: python main.py
    - name: Upload Video
      uses: actions/upload-artifact@v4
      with:
        name: MyFinalVideo
        path: final_video.mp4
